name: Release Please

on:
  push:
    branches: [main]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: your-package-name
          changelog-types: '[
            {"type":"feat","section":"Features","hidden":false},
            {"type":"fix","section":"Bug Fixes","hidden":false},
            {"type":"chore","section":"Miscellaneous","hidden":false},
            {"type":"docs","section":"Documentation","hidden":false},
            {"type":"style","section":"Styles","hidden":true},
            {"type":"refactor","section":"Refactoring","hidden":true},
            {"type":"perf","section":"Performance","hidden":false},
            {"type":"test","section":"Testing","hidden":true},
            {"type":"ci","section":"CI/CD","hidden":true}
            ]'

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v3
        with:
          node-version: 23
        if: ${{ steps.release.outputs.release_created }}

      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
