name: Compress Images

on:
  push:
    paths:
      - 'assets/**'

permissions:
  contents: write

jobs:
  optimize-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install image optimization tools
        run: |
          sudo apt-get update
          sudo apt-get install -y pngquant jpegoptim gifsicle

      - name: Optimize PNGs
        run: find assets -type f -name "*.png" -exec pngquant --force --ext .png {} \;

      - name: Optimize JPGs
        run: find assets -type f -name "*.jpg" -exec jpegoptim --strip-all {} \;

      - name: Optimize JPEGs
        run: find assets -type f -name "*.jpeg" -exec jpegoptim --strip-all {} \;

      - name: Optimize GIFs
        run: find assets -type f -name "*.gif" -exec gifsicle -b -O3 {} \;

      - name: Commit optimized images
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin main
          git rebase origin/main  # safer than merge

          git add assets
          git diff --cached --quiet || git commit -m "chore: optimize images"
          git push origin HEAD:main
