name: Dependency Audit

on:
  pull_request:
  schedule:
    - cron: '0 2 * * 1' # every Monday at 2 AM "minute hour day_of_month month day_of_week"

jobs:
  if: false
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm audit --audit-level=moderate
