name: Auto Format Code with Prettier

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  format:
    runs-on: ubuntu-latest

    # Skip if commit message contains [skip format]
    if: ${{ !contains(github.event.head_commit.message, '[skip format]') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Use a token that can push to protected branches
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check if Prettier is installed
        run: |
          if ! npm list prettier --depth=0 > /dev/null 2>&1; then
            echo "Installing Prettier..."
            npm install --save-dev prettier
          fi

      - name: Run Prettier
        run: |
          # Format all supported files
          npx prettier --write "**/*.{js,jsx,ts,tsx,json,css,scss,md,html,yml,yaml}" \
            --ignore-path .gitignore \
            --ignore-unknown

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Files were formatted by Prettier"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No formatting changes needed"
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "🎨 Auto-format code with Prettier [skip ci]"
          git push

  # Optional: Create a comment on PR with formatting results
  comment-on-pr:
    runs-on: ubuntu-latest
    needs: format
    if: ${{ github.event_name == 'pull_request' && needs.format.outputs.changed == 'true' }}

    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🎨 **Auto-formatting applied!** \n\nYour code has been automatically formatted with Prettier. Please pull the latest changes before continuing your work.\n\n```bash\ngit pull origin ${{ github.head_ref }}\n```'
            })
