# Key Components:

# Complete tool setup with ESLint, Prettier, Husky, and lint-staged
# Detailed configuration files with sensible defaults
# Git hooks for pre-commit and pre-push validation
# CI/CD pipeline integration with GitHub Actions
# IDE integration settings for VS Code

# Enforcement Strategies:

# Automated formatting and linting on save
# Pre-commit hooks that prevent bad code from being committed
# Pull request checks that block merging of non-compliant code
# Branch protection rules and PR templates

# Advanced Features:

# Security analysis with eslint-plugin-security
# Code complexity monitoring with SonarJS
# Custom rule development examples
# Quality metrics reporting
# Troubleshooting guide

name: Auto Format Code with Prettier

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  if: false
  format:
    runs-on: ubuntu-latest

    # Skip if commit message contains [skip format]
    if: ${{ !contains(github.event.head_commit.message, '[skip format]') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Use a token that can push to protected branches
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check if Prettier is installed
        run: |
          if ! npm list prettier --depth=0 > /dev/null 2>&1; then
            echo "Installing Prettier..."
            npm install --save-dev prettier
          fi

      - name: Run Prettier
        run: |
          # Format all supported files
          npx prettier --write "**/*.{js,jsx,ts,tsx,json,css,scss,md,html,yml,yaml}" \
            --ignore-path .gitignore \
            --ignore-unknown

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Files were formatted by Prettier"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No formatting changes needed"
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "🎨 Auto-format code with Prettier [skip ci]"
          git push

  # Optional: Create a comment on PR with formatting results
  comment-on-pr:
    runs-on: ubuntu-latest
    needs: format
    if: ${{ github.event_name == 'pull_request' && needs.format.outputs.changed == 'true' }}

    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🎨 **Auto-formatting applied!** \n\nYour code has been automatically formatted with Prettier. Please pull the latest changes before continuing your work.\n\n```bash\ngit pull origin ${{ github.head_ref }}\n```'
            })

# name: Lint and Format Check

# on:
#   pull_request:
#     branches: [main, develop]
#   push:
#     branches: [main, develop]

# jobs:
#   lint:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '18'
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm ci

#       - name: Run ESLint
#         run: npm run lint

#       - name: Check Prettier formatting
#         run: npm run format:check

#       - name: Security audit
#         run: npm audit --audit-level high

#       - name: Upload ESLint results
#         if: failure()
#         uses: github/super-linter@v4
#         env:
#           DEFAULT_BRANCH: main
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

