name: Build and Test React Application

# What's possible?
# 1. CI/CD - Build, Test, and Deploy
# 2. Github automation - Auto-labeling, PR checks/workflows, release management
# 3. Notifications - Discord/slack/telegram/email/sms/push notifications
# 4. Others - compress images, manage artifacts, conditional steps (only if certain files are changed),
# manual approvals (pause workflows and require human confirmation)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test -- --coverage --watchAll=false

      - name: Build application
        run: npm run build
